<template>
    <page-load id="blacklist">
        <page-title>
            <div class="pull-right">
                <button class="btn btn-success" @click.prevent="showBlacklist">
                    <i class="mdi mdi-check margin-right-5"></i>
                    Generate
                </button>
            </div>

            <img :src="image_path_by_name('item', 'Book (Black)')" class="margin-right-5">
            <div class="title">
                <h2>Blacklist</h2>
                <span>Quick Loot</span>
            </div>
        </page-title>

        <page-load class="no-padding">
            <panel title="How to update the blacklist?" :open="false" toggleable>
                <ol>
                    <li>Login in the Character you want and add a item to blacklist to generate the file.</li>
                    <li>Close the Tibia Client.</li>

                    <b class="margin-top-10 margin-bottom-10 block">Access the folder where blacklist file is located:</b>
                    <li>

                        <code>Windows + R</code>
                        <i class="mdi mdi-arrow-right"></i>
                        <input type="text" class="form-control" value="%localappdata%\Tibia\packages\Tibia\characterdata"
                               style="display: inline-block; width: 390px;">

                        <span class="label label-default">Execute</span>
                    </li>
                    <li>Search the file <code>lootBlackWhitelist.json</code> and open using Notepad</li>
                    <li>Paste the code generated by the tool.</li>
                    <li>Save and close the file</li>
                    <li>You are done!</li>
                </ol>
            </panel>

            <panel class="filter">
                <div class="row">
                    <div class="col-md-3">
                        <el-select v-model="creature"
                                   no-data-text="Creatures not found"
                                   no-match-text="Creature not found"
                                   placeholder="Creature"
                                   filterable
                                   clearable
                                   remote
                                   default-first-option
                                   value-key="id"
                                   :remote-method="findCreature"
                                   @change="changeCreature">
                            <el-option v-for="creature in creatures" :value="creature" :label="creature.title"
                                       :key="creature.id"/>
                        </el-select>
                    </div>

                    <div class="col-md-3">
                        <el-select v-model="category"
                                   no-data-text="Categories not found"
                                   no-match-text="Category not found"
                                   placeholder="Categories"
                                   filterable
                                   @change="filterItem">
                            <el-option v-for="category in categories" :value="category.id" :label="category.title"
                                       :key="category.id"></el-option>
                        </el-select>
                    </div>

                    <div class="col-md-3">
                        <label>Capacity Over</label>
                        <el-slider v-model="capacity" item :min="0" :max="180" :step="10"></el-slider>
                    </div>

                    <div class="col-md-3">
                        <label>Price Range</label>
                        <el-slider v-model="value" range :min="0" :max="200000" :step="10000"></el-slider>
                    </div>
                </div>
            </panel>

            <panel class="items">
                <page-load class="no-padding" :loading="loadingItems">
                    <div class="col-md-2" v-for="item in items">
                        <div class="item" :class="{ 'active': isSelected(item.identifier) }"
                             @click.prevent="toggleItem(item.identifier)">
                            <div class="thumb">
                                <img :src="image_path('item', item.id)">
                            </div>
                            <span class="name">{{ item.title }}</span>
                        </div>
                    </div>
                </page-load>
            </panel>

            <small>
                Credit for <a href="https://www.reddit.com/user/RydanTV">RydanTV</a>
                for providing the id of lootable items.
            </small>
        </page-load>

        <blacklist :blacklist="blacklist"/>
    </page-load>
</template>

<script>
    import Blacklist from './Blacklist'
    import services from '../services'
    import { debounce } from 'lodash'

    export default {
        components: { Blacklist },

        data () {
            return {
                loading: true,
                loadingItems: true,
                itemsList: [],
                capacity: 0,
                value: [0, 1000000],
                creature: '',
                creatures: [],
                category: 1,
                categories: [{ id: 0, title: 'All' }],
                blacklist: {
                    "blacklistTypes": [],
                    "listType": "blacklist",
                    "whitelistTypes": []
                },
                blacklistVisible: false,
            }
        },

        computed: {
            items () {
                return typeof this.category == 'number'
                    ? (this.category != 0
                        ? this.itemsList.filter(item => item.category_id == this.category)
                        : this.itemsList)
                    .filter(item => item.actual_value >= this.value[0] && item.actual_value <= this.value[1])
                    .filter(item => item.capacity >= this.capacity)
                    : this.itemsList
            }
        },

        methods: {
            findCreature: debounce(function (query) {
                if (query.length) {
                    services.getCreature(query)
                        .then(response => {
                            this.creatures = response.data
                        })
                } else {
                    this.creatures = []
                    this.creature = ''
                }
            }, 300),

            changeCreature () {
                this.category = this.creature == null || this.creature == '' ? 1 : 0

                this.filterItem()
            },

            isSelected (identifier) {
                return this.blacklist.blacklistTypes.indexOf(identifier) != - 1
            },

            toggleItem (identifier) {
                if (this.blacklist.blacklistTypes.indexOf(identifier) != - 1) {
                    const index = this.blacklist.blacklistTypes.indexOf(identifier)
                    this.blacklist.blacklistTypes.splice(index, 1)
                } else {
                    this.blacklist.blacklistTypes.push(identifier)
                }
            },

            showBlacklist () {
                this.$root.$emit('generate::blacklist')
            },

            filterItem () {
                const creature = this.creature.id
                const category = this.category

                this.loadingItems = true
                services.getItems(creature, category)
                    .then(response => {
                        this.itemsList = response.data
                        this.loadingItems = false
                    })
                    .catch(() => this.loadingItems = false)
            },
        },

        mounted () {
            services.getCategories()
                .then(response => {
                    this.categories.push(...response.data)
                    this.filterItem()
                })
                .catch(() => this.loading = false)
        }
    }
</script>