<template>
    <page-load>
        <page-title>
            <img :src="image_path_by_name('item', 'memory box')" class="margin-right-10">
            <div class="title">
                <h2>Database Sync</h2>
                <span>Syncronize Updates</span>
            </div>
        </page-title>

        <panel>
            <div class="alert alert-warning">
                The syncronizer can take a while to finish.
            </div>

            <p>
                The database syncronize will get all information from database.db (the file generated by database scan), and
                will update all npcs, items, creatures, categories and more in the database.
            </p>

            <button class="btn margin-top-20" :class="[fail ? 'btn-danger' : 'btn-success']" @click.prevent="syncronize" :disabled="syncing">
                <span class="loader inline button margin-right-5" v-if="syncing"></span>
                <i class="mdi margin-right-5" :class="[fail ? 'mdi-close-circle' : 'mdi-sync']" v-else></i>

                {{ status }}
            </button>
        </panel>
    </page-load>
</template>

<script>
    import services from '../services'

    export default {
        data () {
            return {
                syncing: false,
                status: 'Syncronize Database',
                fail: false
            }
        },

        methods: {
            syncronize () {
                this.status = 'Syncronizing NPC\'s'
                this.syncing = true

                services.syncNPCs()
                    .then (response => {
                        this.status = 'Syncronizing Categories'
                        this.fail = false

                        services.syncCategories()
                            .then (response => {
                                this.status = 'Syncronizing Items'
                                this.fail = false

                                services.syncItems()
                                    .then (response => {
                                        this.status = 'Syncronizing Creatures'
                                        this.fail = false

                                        services.syncCreatures()
                                            .then (response => {
                                                this.status = 'Syncronizing Tiles'
                                                this.fail = false

                                                services.syncTiles()
                                                    .then (response => {
                                                        this.syncing = false
                                                        this.status = 'Done'
                                                        this.fail = false
                                                    })
                                                    .catch (() => {
                                                        this.syncing = false
                                                        this.status = 'Syncronization Failed'
                                                        this.fail = true
                                                    })
                                            })
                                            .catch (() => {
                                                this.syncing = false
                                                this.status = 'Syncronization Failed'
                                                this.fail = true
                                            })
                                    })
                                    .catch (() => {
                                        this.syncing = false
                                        this.status = 'Syncronization Failed'
                                        this.fail = true
                                    })
                            })
                            .catch (() => {
                                this.syncing = false
                                this.status = 'Syncronization Failed'
                            })
                    })
                    .catch (() => {
                        this.syncing = false
                        this.status = 'Syncronize Database'
                    })
            }
        }

    }
</script>