export default {
    helmet: [
        { label: 'Basic Shielding', value: { property: 'shielding', value: 1 } },
        { label: 'Intricate Shielding', value: { property: 'shielding', value: 2 } },
        { label: 'Powerful Shielding', value: { property: 'shielding', value: 4 } },
        { label: 'Basic Magic Level', value: { property: 'magic level', value: 1 } },
        { label: 'Intricate Magic Level', value: { property: 'magic level', value: 2 } },
        { label: 'Powerful Magic Level', value: { property: 'magic level', value: 4 } },
        { label: 'Basic Axe Fighting', value: { property: 'axe fighting', value: 1 } },
        { label: 'Intricate Axe Fighting', value: { property: 'axe fighting', value: 2 } },
        { label: 'Powerful Axe Fighting', value: { property: 'axe fighting', value: 4 } },
        { label: 'Basic Club Fighting', value: { property: 'club fighting', value: 1 } },
        { label: 'Intricate Club Fighting', value: { property: 'club fighting', value: 2 } },
        { label: 'Powerful Club Fighting', value: { property: 'club fighting', value: 4 } },
        { label: 'Basic Sword Fighting', value: { property: 'sword fighting', value: 1 } },
        { label: 'Intricate Sword Fighting', value: { property: 'sword fighting', value: 2 } },
        { label: 'Powerful Sword Fighting', value: { property: 'sword fighting', value: 4 } },
        { label: 'Basic Distance Fighting', value: { property: 'distance fighting', value: 1 } },
        { label: 'Intricate Distance Fighting', value: { property: 'distance fighting', value: 2 } },
        { label: 'Powerful Distance Fighting', value: { property: 'distance fighting', value: 4 } },
    ],

    armor: [
        { label: 'Basic Death Protection', value: { property: 'death', value: 0.02 } },
        { label: 'Intricate Death Protection', value: { property: 'death', value: 0.05 } },
        { label: 'Powerful Death Protection', value: { property: 'death', value: 0.1 } },
        { label: 'Basic Earth Protection', value: { property: 'earth', value: 0.03 } },
        { label: 'Intricate Earth Protection', value: { property: 'earth', value: 0.08 } },
        { label: 'Powerful Earth Protection', value: { property: 'earth', value: 0.15 } },
        { label: 'Basic Fire Protection', value: { property: 'fire', value: 0.03 } },
        { label: 'Intricate Fire Protection', value: { property: 'fire', value: 0.08 } },
        { label: 'Powerful Fire Protection', value: { property: 'fire', value: 0.15 } },
        { label: 'Basic Ice Protection', value: { property: 'ice', value: 0.03 } },
        { label: 'Intricate Ice Protection', value: { property: 'ice', value: 0.08 } },
        { label: 'Powerful Ice Protection', value: { property: 'ice', value: 0.15 } },
        { label: 'Basic Energy Protection', value: { property: 'energy', value: 0.03 } },
        { label: 'Intricate Energy Protection', value: { property: 'energy', value: 0.08 } },
        { label: 'Powerful Energy Protection', value: { property: 'energy', value: 0.15 } },
        { label: 'Basic Holy Protection', value: { property: 'holy', value: 0.03 } },
        { label: 'Intricate Holy Protection', value: { property: 'holy', value: 0.08 } },
        { label: 'Powerful Holy Protection', value: { property: 'holy', value: 0.15 } },
    ],

    shield: [
        { label: 'Basic Death Protection', value: { property: 'death', value: 0.02 } },
        { label: 'Intricate Death Protection', value: { property: 'death', value: 0.05 } },
        { label: 'Powerful Death Protection', value: { property: 'death', value: 0.1 } },
        { label: 'Basic Earth Protection', value: { property: 'earth', value: 0.03 } },
        { label: 'Intricate Earth Protection', value: { property: 'earth', value: 0.08 } },
        { label: 'Powerful Earth Protection', value: { property: 'earth', value: 0.15 } },
        { label: 'Basic Fire Protection', value: { property: 'fire', value: 0.03 } },
        { label: 'Intricate Fire Protection', value: { property: 'fire', value: 0.08 } },
        { label: 'Powerful Fire Protection', value: { property: 'fire', value: 0.15 } },
        { label: 'Basic Ice Protection', value: { property: 'ice', value: 0.03 } },
        { label: 'Intricate Ice Protection', value: { property: 'ice', value: 0.08 } },
        { label: 'Powerful Ice Protection', value: { property: 'ice', value: 0.15 } },
        { label: 'Basic Energy Protection', value: { property: 'energy', value: 0.03 } },
        { label: 'Intricate Energy Protection', value: { property: 'energy', value: 0.08 } },
        { label: 'Powerful Energy Protection', value: { property: 'energy', value: 0.15 } },
        { label: 'Basic Holy Protection', value: { property: 'holy', value: 0.03 } },
        { label: 'Intricate Holy Protection', value: { property: 'holy', value: 0.08 } },
        { label: 'Powerful Holy Protection', value: { property: 'holy', value: 0.15 } },
        { label: 'Basic Shielding', value: { property: 'shielding', value: 1 } },
        { label: 'Intricate Shielding', value: { property: 'shielding', value: 2 } },
        { label: 'Powerful Shielding', value: { property: 'shielding', value: 4 } },
    ]
}