export default {
    atk: 'Atk',
    def: 'Def',
    arm: 'Arm',
    hit: 'Hit Chance',
    vol: 'Volume',
    death: 'Death Protection',
    earth: 'Earth Protection',
    energy: 'Energy Protection',
    fire: 'Fire Protection',
    ice: 'Ice Protection',
    speed: 'Speed',
    level: 'Level Required',
    shielding: 'Shielding',
    range: 'Range',
    weight: 'Weight',
    imbuements: 'Imbuements Slots',
    'two-handed': 'Two Handed',
    'magic level': 'Magic Level',
    'mana drain': 'Mana Drain Protection',
    'life drain': 'Life Drain Protection',
    'axe fighting': 'Axe Fighting',
    'club fighting': 'Club Fighting',
    'sword fighting': 'Sword Fighting',
    'distance fighting': 'Distance Fighting',
    'protection physical': 'Physical Protection'
}